### ISSUE TITLE
Regarding employing other package.

### ISSUE THREAD

**Issue by YunwooLee94** [icsl-Jeon/simple-cmake-package#1]
If one wishes to use an external package and build it alongside the current package, what codes should be added in CMakeLists.txt? For instance, if one desires to utilize the PCL library.

**Comment by icsl-Jeon** [comment]
Please refer my previous page  🙌
https://github.com/icsl-Jeon/hsv_target_localization/blob/master/CMakeLists.txt

**Comment by YunwooLee94** [comment]
Is the package private? I can not access it
[image: Screenshot from 2023-05-01 12-09-36.png]
.

**Comment by icsl-Jeon** [comment]
![image](https://user-images.githubusercontent.com/30062474/235403041-5a546864-e9df-4c98-b20d-8dce014df379.png)
